SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#player ship
PLAYER_RADIUS = 20
LINE_WIDTH = 2

#moving around a and d keys  
PLAYER_TURN_SPEED = 300

#moving, w and s keys
PLAYER_SPEED = 200 

#asteroids 
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
